create extension if not exists pgcrypto;

create table if not exists public.brands (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  slug text not null unique,
  slogan text,
  parent text,
  crs integer not null default 0,
  assets_count integer not null default 0,
  users_count integer not null default 0,
  socials jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brand_members (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  email text not null,
  role text not null check (role in ('admin', 'operador', 'cliente')),
  status text not null default 'activo' check (status in ('activo', 'sin confirmar')),
  invited_label text not null default 'pendiente',
  last_access_label text not null default '-',
  created_at timestamptz not null default now(),
  unique (brand_id, email)
);

create table if not exists public.brand_fichas (
  brand_id uuid primary key references public.brands(id) on delete cascade,
  content text not null,
  format_meta jsonb not null default '{}'::jsonb,
  active_version integer not null default 1,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.brand_ficha_versions (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  version integer not null,
  content text not null,
  format_meta jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (brand_id, version)
);

create table if not exists public.creatives (
  id bigint primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  kind text not null check (kind in ('cover', 'motion', 'carrusel', 'ugc')),
  status text not null check (status in ('aprobado', 'para revision', 'observado', 'borrador', 'para publicar')),
  format text not null check (format in ('Feed 4:5', 'Story 9:16', 'Carrusel')),
  title text not null,
  headline text not null,
  subhead text not null default '',
  copy text not null default '',
  caption text not null default '',
  visual_cue text not null default '',
  palette text not null default '#46515A',
  tags text[] not null default '{}',
  pipeline jsonb not null default '[]'::jsonb,
  pipeline_meta jsonb not null default '{}'::jsonb,
  render_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ideas (
  id text not null,
  brand_id uuid not null references public.brands(id) on delete cascade,
  status text not null check (status in ('usada', 'disponible')),
  title text not null,
  category text not null,
  skill text not null,
  trigger text not null,
  phrases text[] not null default '{}',
  anchor text not null default '',
  notes text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (brand_id, id)
);

create table if not exists public.requirements (
  id bigint generated by default as identity primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  date_label text not null,
  status text not null default 'pendiente' check (status in ('pendiente', 'resuelto')),
  title text not null,
  detail text not null default '',
  asset text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.publications (
  id bigint primary key,
  brand_id uuid not null references public.brands(id) on delete cascade,
  creative_id bigint references public.creatives(id) on delete set null,
  date date not null,
  day integer not null,
  time text not null,
  channel text not null check (channel in ('Instagram', 'Facebook', 'LinkedIn', 'TikTok')),
  format text not null check (format in ('Feed 4:5', 'Story 9:16', 'Carrusel')),
  status text not null check (status in ('programada', 'publicada', 'borrador')),
  title text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.assets (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references public.brands(id) on delete cascade,
  type text not null default 'otro',
  name text not null,
  url text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_items (
  code text not null,
  brand_id uuid not null references public.brands(id) on delete cascade,
  title text not null,
  status text not null check (status in ('critico', 'pendiente', 'aplicado')),
  category text not null check (category in ('Marca', 'Contenido', 'SEO', 'Performance', 'Conversión')),
  note text not null default '',
  created_at timestamptz not null default now(),
  primary key (brand_id, code)
);

create or replace function public.is_brand_member(target_brand_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.brand_members bm
    where bm.brand_id = target_brand_id
      and (
        bm.user_id = auth.uid()
        or lower(bm.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
  );
$$;

create or replace function public.has_brand_role(target_brand_id uuid, allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.brand_members bm
    where bm.brand_id = target_brand_id
      and bm.role = any(allowed_roles)
      and (
        bm.user_id = auth.uid()
        or lower(bm.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
  );
$$;

alter table public.brands enable row level security;
alter table public.brand_members enable row level security;
alter table public.brand_fichas enable row level security;
alter table public.brand_ficha_versions enable row level security;
alter table public.creatives enable row level security;
alter table public.ideas enable row level security;
alter table public.requirements enable row level security;
alter table public.publications enable row level security;
alter table public.assets enable row level security;
alter table public.audit_items enable row level security;

drop policy if exists "members can read brands" on public.brands;
create policy "members can read brands" on public.brands
for select to authenticated
using (public.is_brand_member(id));

drop policy if exists "members can read memberships" on public.brand_members;
create policy "members can read memberships" on public.brand_members
for select to authenticated
using (public.is_brand_member(brand_id));

drop policy if exists "admins can manage memberships" on public.brand_members;
create policy "admins can manage memberships" on public.brand_members
for all to authenticated
using (public.has_brand_role(brand_id, array['admin']))
with check (public.has_brand_role(brand_id, array['admin']));

drop policy if exists "members can read fichas" on public.brand_fichas;
create policy "members can read fichas" on public.brand_fichas
for select to authenticated
using (public.is_brand_member(brand_id));

drop policy if exists "operators can edit fichas" on public.brand_fichas;
create policy "operators can edit fichas" on public.brand_fichas
for all to authenticated
using (public.has_brand_role(brand_id, array['admin', 'operador']))
with check (public.has_brand_role(brand_id, array['admin', 'operador']));

drop policy if exists "members can read ficha versions" on public.brand_ficha_versions;
create policy "members can read ficha versions" on public.brand_ficha_versions
for select to authenticated
using (public.is_brand_member(brand_id));

drop policy if exists "operators can insert ficha versions" on public.brand_ficha_versions;
create policy "operators can insert ficha versions" on public.brand_ficha_versions
for insert to authenticated
with check (public.has_brand_role(brand_id, array['admin', 'operador']));

drop policy if exists "members can read creatives" on public.creatives;
create policy "members can read creatives" on public.creatives
for select to authenticated
using (public.is_brand_member(brand_id));

drop policy if exists "operators can update creatives" on public.creatives;
create policy "operators can update creatives" on public.creatives
for update to authenticated
using (public.has_brand_role(brand_id, array['admin', 'operador']))
with check (public.has_brand_role(brand_id, array['admin', 'operador']));

drop policy if exists "members can read ideas" on public.ideas;
create policy "members can read ideas" on public.ideas
for select to authenticated
using (public.is_brand_member(brand_id));

drop policy if exists "operators can manage ideas" on public.ideas;
create policy "operators can manage ideas" on public.ideas
for all to authenticated
using (public.has_brand_role(brand_id, array['admin', 'operador']))
with check (public.has_brand_role(brand_id, array['admin', 'operador']));

drop policy if exists "members can read requirements" on public.requirements;
create policy "members can read requirements" on public.requirements
for select to authenticated
using (public.is_brand_member(brand_id));

drop policy if exists "members can create requirements" on public.requirements;
create policy "members can create requirements" on public.requirements
for insert to authenticated
with check (public.is_brand_member(brand_id));

drop policy if exists "operators can update requirements" on public.requirements;
create policy "operators can update requirements" on public.requirements
for update to authenticated
using (public.has_brand_role(brand_id, array['admin', 'operador']))
with check (public.has_brand_role(brand_id, array['admin', 'operador']));

drop policy if exists "members can read publications" on public.publications;
create policy "members can read publications" on public.publications
for select to authenticated
using (public.is_brand_member(brand_id));

drop policy if exists "operators can manage publications" on public.publications;
create policy "operators can manage publications" on public.publications
for all to authenticated
using (public.has_brand_role(brand_id, array['admin', 'operador']))
with check (public.has_brand_role(brand_id, array['admin', 'operador']));

drop policy if exists "members can read assets" on public.assets;
create policy "members can read assets" on public.assets
for select to authenticated
using (public.is_brand_member(brand_id));

drop policy if exists "members can create assets" on public.assets;
create policy "members can create assets" on public.assets
for insert to authenticated
with check (public.is_brand_member(brand_id));

drop policy if exists "members can read audit items" on public.audit_items;
create policy "members can read audit items" on public.audit_items
for select to authenticated
using (public.is_brand_member(brand_id));
